#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

for my $event (qw(
    bootstrap-console-save
    console-save
    post-upgrade
    ))

{
    templates2events("/opt/rh/php54/root/etc/php.ini", $event);
    templates2events("/opt/rh/php55/root/etc/php.ini", $event);
}
